name: open-detect
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: hecrj/setup-rust-action@v2

      - name: Test
        run: cargo test

      - name: Doc Test
        run: cargo test --doc
